import { useEffect, useRef, useState } from "react";
import L from "leaflet";
import "leaflet/dist/leaflet.css";

export default function LeafletMap() {
  const mapContainer = useRef(null);
  const map = useRef(null);
  const center = { lng: 102.6, lat: 17.9667 };
  const [zoom] = useState(11);

  useEffect(() => {
    if (map.current) return; // stops map from intializing more than once

    const osm = L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
      attribution:
        '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    });
    const openTopoMap = L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png', {
      maxZoom: 19,
      attribution: 'Map data: © OpenStreetMap contributors, SRTM | Map style: © OpenTopoMap (CC-BY-SA)'
    });
    const provinces = L.tileLayer.wms(`${import.meta.env.VITE_GEOMAP_WMS_URL}`, {
      maxZoom: 20,
      layers: 'lvis:province',
      transparent:true,
      styles: 'provinces',
      format:'image/png',
      opacity: 0.6,
      attribution: 'Map data: © Generated by Lao Land Valuation Team'});

    const districts = L.tileLayer.wms(`${import.meta.env.VITE_GEOMAP_WMS_URL}`, {
      maxZoom: 20,
      layers: 'lvis:district',
      transparent:true,
      styles: 'districts',
      format:'image/png',
      opacity: 0.8,
      attribution: 'Map data: © Generated by Lao Land Valuation Team'});

    var baseMaps = {
      "OpenStreetMap": osm
    };
    var overlayMaps = {
      "Provinces": provinces,
      "Districts": districts,
    };

    map.current = new L.Map(mapContainer.current, {
      center: L.latLng(center.lat, center.lng),
      zoom: zoom,
      layers: [osm, provinces]
    });
    var layerControl = L.control.layers(baseMaps, overlayMaps).addTo(map.current);
    layerControl.addBaseLayer(openTopoMap, "OpenTopoMap");
  }, [center.lng, center.lat, zoom]);



  return (
    <div className="map-wrap" style={{ height: "100%", zIndex: 0 }}>
      <div ref={mapContainer} className="map" />
    </div>
  );
}
