import React, { useState, useEffect } from 'react';
import { MapContainer, TileLayer, ScaleControl, WMSTileLayer, LayerGroup, useMap } from 'react-leaflet';
import { useTheme } from '@mui/material';
import 'leaflet/dist/leaflet.css';
import Toolbar from "./toolbar/Toolbar"

const StyledGridLayer = () => {
  const map = useMap();
  useEffect(() => {
    const StyledGrid = L.GridLayer.extend({
      createTile: function (coords) {
        var tile = L.DomUtil.create("canvas", "leaflet-tile");
        var ctx = tile.getContext("2d");
        var size = this.getTileSize();
        tile.width = size.x;
        tile.height = size.y;
        // calculate projection coordinates of top left tile pixel
        var nwPoint = coords.scaleBy(size);
        // calculate geographic coordinates of top left tile pixel
        var nw = map.unproject(nwPoint, coords.z);
        ctx.fillStyle = "white";
        ctx.fillRect(0, 0, size.x, 50);
        ctx.fillStyle = "black";
        ctx.fillText(
          "x: " + coords.x + ", y: " + coords.y + ", zoom: " + coords.z,
          20,
          20
        );
        ctx.fillText("lat: " + nw.lat + ", lon: " + nw.lng, 20, 40);
        ctx.strokeStyle = "red";
        ctx.beginPath();
        ctx.moveTo(0, 0);
        ctx.lineTo(size.x - 1, 0);
        ctx.lineTo(size.x - 1, size.y - 1);
        ctx.lineTo(0, size.y - 1);
        ctx.closePath();
        ctx.stroke();
        return tile;
      }
    });

    const StyledGridLayer = new StyledGrid({
      transparent: true,
      opacity: 0.8,
      zIndex: 100,
      attribution: "Map data: © Generated by Lao Land Valuation Team",
    });
    StyledGridLayer.addTo(map);

    return () => {
      map.removeLayer(StyledGridLayer); // Clean up the layer when the component unmounts
    };
  }, [map]);

  return null;
};
const WatermarkControl = ({ theme, imgUrl, text }) => {
  const map = useMap();
  useEffect(() => {
    const Watermark = L.Control.extend({
      onAdd: () => {
        const div = L.DomUtil.create('div', 'leaflet-watermark');
        if (imgUrl) {
          const img = document.createElement('img');
          img.src = imgUrl;
          img.style.width  = '40px'; // Adjust as needed
          div.appendChild(img);
        }
        if (text) {
          const watermarkText = document.createElement('div');
          watermarkText.innerHTML = text;
          watermarkText.style.fontSize = '12px';
          watermarkText.style.color = theme.palette.background.alt;
          watermarkText.style.fontWeight = 'bold';
          watermarkText.style.backgroundColor = 'transparent';
          //watermarkText.style.padding = '1px 0px 0px 0px';
          div.appendChild(watermarkText);
        }
        return div;
      },
      onRemove: () => { }
    });

    const watermarkControl = new Watermark({ position: 'bottomleft' });
    map.addControl(watermarkControl);

    return () => {
      map.removeControl(watermarkControl); // Clean up on component unmount
    };
  }, [map, imgUrl, text]);

  return null;
};
const ValuationMap = () => {
  const [center, setCenter] = useState({ lat: 19.8563, lng: 102.4955 });
  const [map, setMap] = useState(null);
  const theme = useTheme();
  const [baseLayers, setBaseLayers] = useState([
    { name: 'Open Street Map', active: true },
    { name: 'Open Topo Map', active: false },
  ]);
  const handleBaseLayerChange = (layerName) => {
    setBaseLayers((prev) =>
      prev.map((layer) =>
        layer.name === layerName
          ? { ...layer, active: true }
          : { ...layer, active: false }
      )
    );
  };
  const [overlays, setOverlays] = useState([
    { name: 'Province', visible: true },
    { name: 'District', visible: true },
    { name: 'Village', visible: true },
    { name: 'Road', visible: false },
    { name: 'Parcel', visible: false },
    { name: 'Valuation Object', visible: false },
    { name: 'Grid Cell', visible: false },
  ]);
  const handleOverlayToggle = (layerName) => {
    setOverlays((prev) =>
      prev.map((layer) =>
        layer.name === layerName
          ? { ...layer, visible: !layer.visible }
          : layer
      )
    );
  };
  return (
    <div style={{ position: 'relative', height: '100vh' }}>
      <MapContainer
        center={center}
        zoomControl={false}
        zoom={9}
        style={{ height: '100%', width: '100%' }}
        ref={setMap}
      >
        {/* Base Layers */}
        {baseLayers[0].active && (
          <TileLayer
            url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
            attribution="Open Street Map"
            zIndex={1}
          />
        )}
        {baseLayers[1].active && (
          <TileLayer
            url="https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png"
            attribution="Open Topo Map"
            zIndex={1}
          />
        )}
        {/* Ovarlay Layers */}
        <LayerGroup>
          {overlays[0].visible && (
            <WMSTileLayer
              layers={"lvis:province"}
              url={import.meta.env.VITE_GEOMAP_WMS_URL}
              maxZoom={20}
              transparent={true}
              styles="province"
              format="image/png"
              opacity={0.6}
              zIndex={2}
            />
          )}
          {overlays[1].visible && (
            <WMSTileLayer
              layers={"lvis:district"}
              url={import.meta.env.VITE_GEOMAP_WMS_URL}
              maxZoom={20}
              transparent={true}
              styles="district"
              format="image/png"
              opacity={0.8}
              zIndex={3}
            />
          )}
          {overlays[2].visible && (
            <WMSTileLayer
              layers={"lvis:village"}
              url={import.meta.env.VITE_GEOMAP_WMS_URL}
              maxZoom={20}
              transparent={true}
              styles="village"
              format="image/png"
              opacity={0.85}
              zIndex={4}
            />
          )}
          {overlays[3].visible && (
            <WMSTileLayer
              layers={"lvis:road"}
              url={import.meta.env.VITE_GEOMAP_WMS_URL}
              maxZoom={20}
              transparent={true}
              styles="road"
              format="image/png"
              opacity={1}
              layerName="Road"
              zIndex={5}
            />
          )}
          {overlays[4].visible && (
            <WMSTileLayer
              layers={"lvis:parcel_re"}
              url={import.meta.env.VITE_GEOMAP_WMS_URL_BK}
              maxZoom={20}
              transparent={true}
              format="image/png"
              opacity={0.6}
              zIndex={6}
            />
          )}
          {overlays[5].visible && (
            <WMSTileLayer
              layers={"lvis:parcel_tech"}
              url={import.meta.env.VITE_GEOMAP_WMS_URL_BK}
              maxZoom={20}
              transparent={true}
              styles="parcel_tech"
              tiled={true}
              format="image/png"
              opacity={0.6}
              zIndex={6}
              attribution="Map data: © Generated by Lao Land Valuation Team"
            />
          )}
          {overlays[6].visible && (
            <StyledGridLayer />
          )}
        </LayerGroup>
        <Toolbar
          baseLayers={baseLayers}
          overlays={overlays}
          onBaseLayerChange={handleBaseLayerChange}
          onOverlayToggle={handleOverlayToggle}
        />
        <WatermarkControl
          theme={theme}
          imgUrl="./org.png" // Replace with your image URL
          text="MONRE"
        />
        <ScaleControl position="bottomright" imperial={false} />
      </MapContainer>
    </div>
  );
};

export default ValuationMap;