package com.jdvn.devtech.datamodel.schema.preparation;

import java.util.Date;

import org.hibernate.annotations.Comment;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Entity
@DynamicInsert
@DynamicUpdate
@Table(name = "model_coefficient", schema = "preparation")
@Comment("Used to store the calculated coefficients of regression model.")
public class ModelHasCoefficient {

	@Id
	@Comment("Identifier of the coefficient for model.")
	@Column(nullable = false, columnDefinition = "character varying(40) DEFAULT public.uuid_generate_v1()")
	private String id;

	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "model_id", foreignKey = @ForeignKey(name = "model_coefficients_model_id_fkey"))
	@Comment("The id of the model associated. If the coefficient is not generated by a model of mass appraisal procedures it can be NULL as this coefficient is almost predefined for a parameter in a formula.")
	private ValuationModel model;

	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "parameter_code", foreignKey = @ForeignKey(name = "model_coefficients_code_fkey"))
	@Comment("The code of the technical parameter.")
	private TechnicalParameter technical_parameter;

	@Comment("Minimum value of the coefficient.")
	private Double range_from;

	@Comment("Maximum value of the coefficient.")
	private Double range_to;

	@Column(columnDefinition = "numeric(20,2) NOT NULL DEFAULT 0")
	@Comment("Value of the coefficient corresponding with parameter code.")
	private Double coefficient_value;

	@Comment("The date that coefficient is valid.")
	private Date valid_from;

	@Comment("The date that coefficient is retired.")
	private Date valid_to;
}