name: Build & Deployment MERN Stack for UI Prototype

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.16.0
        cache-dependency-path: './stages/server0/package-lock.json'
        cache: 'npm'
    - name: Install node_modules for server0
      working-directory: ./stages/server0
      run: npm i --legacy-peer-deps
    - name: Build server0
      working-directory: ./stages/server0
      run: npm run build --if-present
    - name: Install node_modules for lvis-ui0
      working-directory: ./stages/lvis-ui0
      run: npm i
    - name: Build lvis-ui0
      working-directory: ./stages/lvis-ui0
      run: npm run build --if-present
